version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /update
  script: main.app

- url: /email
  script: main.app

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /images
  static_dir: assets/images

- url: /.*
  script: main.app
#  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
